# Generated by Django 4.2.27 on 2026-01-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0002_task_sort_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="text",
            new_name="name",
        ),
    ]
