# Generated by Django 4.2.27 on 2026-01-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0003_rename_text_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="sort_order",
            new_name="order",
        ),
    ]
