# Generated by Django 6.0.3 on 2026-04-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0004_rename_sort_order_task_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
