# Generated by Django 6.0.3 on 2026-04-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0005_rename_parent_task_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='type',
            new_name='type_link',
        ),
    ]
